; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:black_f407ze]
platform = ststm32
board = black_f407ze
framework = stm32cube
lib_ldf_mode = deep+
build_flags = 
    -I include/
    -I inc/
    -I Inc/
    -I src/Middlewares/Third_Party/FreeRTOS/Source/include/
    -I src/Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F/
    -I src/Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2/
    
    ; Включаем FPU для Cortex-M4F
    -mcpu=cortex-m4   ; Архитектура
    -mfpu=fpv4-sp-d16 ; FPU настройки - критически важно!
    -mfloat-abi=softfp ; FPU настройки - критически важно!

    ; внeшняя либа для fpu #include <arm_math.h> https://github.com/platformio/platform-ststm32/issues/591
    -larm_cortexM4l_math
    
    ; compiler and library support for the ISO C++ 2017 standard
    -std=gnu++17
    
    ; Оптимизация
    ; -Os
    ; -ffunction-sections
    ; -fdata-sections
    ; -fno-use-cxa-atexit ;  warning: command line option '-fno-use-cxa-atexit' is valid for C++/ObjC++ but not for C



;  Пути для линковки (если есть статические библиотеки)
build_src_flags =
    -L src/Middlewares/Third_Party/FreeRTOS/Source/
    -L src/Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2/
    -L src/Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F/
    -L src/Middlewares/Third_Party/FreeRTOS/Source/portable/MemMang/



; Настройка монитора для просмотсра логов
monitor_speed = 115200   ; ← вот это важно!
monitor_port = COM4      ; ← вот это важно!
;  Known filters are `debug, default, direct, hexlify, log2file, nocontrol, printable, send_on_enter, time`

; ===========================
; Configuring upload protocol
; AVAILABLE: blackmagic, cmsis-dap, jlink, serial, stlink

; Настройки для J-Link
upload_protocol = jlink
debug_tool = jlink

; upload_protocol = stlink
; debug_tool = stlink
